# the target is in the format of "({filename}, {line_number}, {function_name})"
TARGETS = {
    "lark-parser": {
        "easy": {
            "lark:lark.py:365": ("lark/lark.py", 365, "Lark::__init__"),
            "lark:lark.py:376": ("lark/lark.py", 376, "Lark::__init__"),
            "lark:lark.py:395": ("lark/lark.py", 395, "Lark::__init__"),
            "lark:lexer.py:348": ("lark/lexer.py", 348, "_create_unless"),
            "lark:lexer.py:381": ("lark/lexer.py", 381, "Scanner::_build_mres"),
            "lark:load_grammar.py:518": ("lark/load_grammar.py", 518, "ApplyTemplates::__init__"),
            "lark:load_grammar.py:707": ("lark/load_grammar.py", 707, "Grammar::compile"),
            "lark:load_grammar.py:788": ("lark/load_grammar.py", 788, "Grammar::compile"),
            "lark:load_grammar.py:806": ("lark/load_grammar.py", 806, "Grammar::compile"),
            "lark:load_grammar.py:887": ("lark/load_grammar.py", 887, "resolve_term_references"),
        },
        "medium": {
            "lark:load_grammar.py:658": ("lark/load_grammar.py", 658, "TerminalTreeToPattern::maybe"),
            "lark:load_grammar.py:661": ("lark/load_grammar.py", 661, "TerminalTreeToPattern::alias"),
            "lark:load_grammar.py:777": ("lark/load_grammar.py", 777, "Grammar::compile"),
            "lark:load_grammar.py:778": ("lark/load_grammar.py", 778, "Grammar::compile"),
            "lark:load_grammar.py:780": ("lark/load_grammar.py", 780, "Grammar::compile"),
            "lark:load_grammar.py:785": ("lark/load_grammar.py", 785, "Grammar::compile"),
            "lark:load_grammar.py:1167": ("lark/load_grammar.py", 1167, "GrammarBuilder::_ignore"),
            "lark:load_grammar.py:1169": ("lark/load_grammar.py", 1169, "GrammarBuilder::_ignore"),
            "lark:load_grammar.py:1170": ("lark/load_grammar.py", 1170, "GrammarBuilder::_ignore"),
            "lark:utils.py:169": ("lark/utils.py", 169, "_test_unicode_category"),
        },
        "hard": {
            "lark:load_grammar.py:305": ("lark/load_grammar.py", 305, "EBNF_to_BNF::_add_repeat_opt_rule"),
            "lark:load_grammar.py:308": ("lark/load_grammar.py", 308, "EBNF_to_BNF::_add_repeat_opt_rule"),
            "lark:load_grammar.py:338": ("lark/load_grammar.py", 338, "EBNF_to_BNF::_generate_repeats"),
            "lark:load_grammar.py:344": ("lark/load_grammar.py", 344, "EBNF_to_BNF::_generate_repeats"),
            "lark:load_grammar.py:368": ("lark/load_grammar.py", 368, "EBNF_to_BNF::exp"),
        },
        "extreme_hard": {
            "lark:parsers:earley_forest.py:196": ("lark/parsers/earley_forest.py", 196, "TokenNode::__eq__"),
            "lark:parsers:earley_forest.py:337": ("lark/parsers/earley_forest.py", 337, "ForestVisitor::visit"),
            "lark:parsers:earley_forest.py:343": ("lark/parsers/earley_forest.py", 343, "ForestVisitor::visit"),
            "lark:parsers:earley_forest.py:573": ("lark/parsers/earley_forest.py", 573, "ForestToParseTree::transform_symbol_node"),
            "lark:parsers:earley_forest.py:583": ("lark/parsers/earley_forest.py", 583, "ForestToParseTree::transform_intermediate_node"),
        },
        "unreachable": {
            "lark:load_grammar.py:1269": ("lark/load_grammar.py", 1269, "GrammarBuilder::load_grammar"),
            "lark:load_grammar.py:1280": ("lark/load_grammar.py", 1280, "GrammarBuilder::load_grammar"),
            "lark:load_grammar.py:1314": ("lark/load_grammar.py", 1314, "GrammarBuilder::do_import"),
            "lark:load_grammar.py:1351": ("lark/load_grammar.py", 1351, "GrammarBuilder::validate"),
            "lark:load_grammar.py:1369": ("lark/load_grammar.py", 1369, "GrammarBuilder::validate"),
        },
    },
    "bleach": {
        "easy": {
            "bleach:_vendor:html5lib:_tokenizer.py:247": ("bleach/_vendor/html5lib/_tokenizer.py", 247, "HTMLTokenizer.emitCurrentToken"),
            "bleach:_vendor:html5lib:_tokenizer.py:263": ("bleach/_vendor/html5lib/_tokenizer.py", 263, "HTMLTokenizer.dataState"),
            "bleach:_vendor:html5lib:_tokenizer.py:397": ("bleach/_vendor/html5lib/_tokenizer.py", 397, "HTMLTokenizer.tagOpenState"),
            "bleach:_vendor:html5lib:html5parser.py:216": ("bleach/_vendor/html5lib/html5parser.py", 216, "HTMLParser::mainLoop"),
            "bleach:_vendor:html5lib:html5parser.py:318": ("bleach/_vendor/html5lib/html5parser.py", 318, "HTMLParser::parseError"),
            "bleach:_vendor:html5lib:html5parser.py:462": ("bleach/_vendor/html5lib/html5parser.py", 462, "Phase::processStartTag"),
            "bleach:_vendor:html5lib:html5parser.py:970": ("bleach/_vendor/html5lib/html5parser.py", 970, "InBodyPhase::addFormattingElement"),
            "bleach:_vendor:html5lib:html5parser.py:980": ("bleach/_vendor/html5lib/html5parser.py", 980, "InBodyPhase::processEOF"),
            "bleach:_vendor:html5lib:html5parser.py:1000": ("bleach/_vendor/html5lib/html5parser.py", 1000, "InBodyPhase::processCharacters"),
            "bleach:html5lib_shim.py:374": ("bleach/html5lib_shim.py", 374, "BleachHTMLTokenizer.__iter__"),
        },
        "medium": {
            "bleach:_vendor:html5lib:_tokenizer.py:1205": ("bleach/_vendor/html5lib/_tokenizer.py", 1205, "HTMLTokenizer::commentStartDashState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1247": ("bleach/_vendor/html5lib/_tokenizer.py", 1247, "HTMLTokenizer::commentEndDashState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1266": ("bleach/_vendor/html5lib/_tokenizer.py", 1266, "HTMLTokenizer::commentEndState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1333": ("bleach/_vendor/html5lib/_tokenizer.py", 1333, "HTMLTokenizer::beforeDoctypeNameState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1358": ("bleach/_vendor/html5lib/_tokenizer.py", 1358, "HTMLTokenizer::doctypeNameState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1416": ("bleach/_vendor/html5lib/_tokenizer.py", 1416, "HTMLTokenizer::afterDoctypeNameState"),
            "bleach:_vendor:html5lib:html5parser.py:1544": ("bleach/_vendor/html5lib/html5parser.py", 1544, "InBodyPhase::endTagFormatting"),
            "bleach:_vendor:html5lib:html5parser.py:1779": ("bleach/_vendor/html5lib/html5parser.py", 1779, "InTablePhase::startTagInput"),
        },
        "hard": {
            "bleach:_vendor:html5lib:_tokenizer.py:588": ("bleach/_vendor/html5lib/_tokenizer.py", 588, "HTMLTokenizer::scriptDataEndTagNameState"),
            "bleach:_vendor:html5lib:_tokenizer.py:826": ("bleach/_vendor/html5lib/_tokenizer.py", 826, "HTMLTokenizer::scriptDataDoubleEscapedDashDashState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1434": ("bleach/_vendor/html5lib/_tokenizer.py", 1434, "HTMLTokenizer::afterDoctypePublicKeywordState"),
            "bleach:_vendor:html5lib:html5parser.py:1591": ("bleach/_vendor/html5lib/html5parser.py", 1591, "InBodyPhase::endTagOther"),
            "bleach:html5lib_shim.py:580": ("bleach/html5lib_shim.py", 580, "convert_entities"),
        },
        "extreme_hard": {
            "bleach:_vendor:html5lib:_tokenizer.py:1482": ("bleach/_vendor/html5lib/_tokenizer.py", 1482, "HTMLTokenizer::doctypePublicIdentifierDoubleQuotedState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1608": ("bleach/_vendor/html5lib/_tokenizer.py", 1608, "HTMLTokenizer::beforeDoctypeSystemIdentifierState"),
            "bleach:_vendor:html5lib:_tokenizer.py:1635": ("bleach/_vendor/html5lib/_tokenizer.py", 1635, "HTMLTokenizer::doctypeSystemIdentifierDoubleQuotedState"),
        },
        "unreachable": {
            "bleach:_vendor:html5lib:_tokenizer.py:250": ("bleach/_vendor/html5lib/_tokenizer.py", 250, "HTMLTokenizer::emitCurrentToken"),
            "bleach:_vendor:html5lib:html5parser.py:966": ("bleach/_vendor/html5lib/html5parser.py", 966, "InBodyPhase::addFormattingElement"),
            "bleach:_vendor:html5lib:html5parser.py:1378": ("bleach/_vendor/html5lib/html5parser.py", 1378, "InBodyPhase::endTagListItem"),
            "bleach:html5lib_shim.py:470": ("bleach/html5lib_shim.py", 470, "BleachHTMLTokenizer.emitCurrentToken"),
            "bleach:html5lib_shim.py:544": ("bleach/html5lib_shim.py", 544, "convert_entity"),
            "bleach:html5lib_shim.py:588": ("bleach/html5lib_shim.py", 588, "convert_entities"),
            "bleach:html5lib_shim.py:634": ("bleach/html5lib_shim.py", 634, "match_entity"),        
        },
    },
    "html5lib-python": {
        "easy": {
            "html5lib:_tokenizer.py:67": ("html5lib/_tokenizer.py", 67, "HTMLTokenizer.__iter__"),
            "html5lib:_tokenizer.py:150": ("html5lib/_tokenizer.py", 150, "HTMLTokenizer::consumeEntity"),
            "html5lib:_tokenizer.py:263": ("html5lib/_tokenizer.py", 263, "HTMLTokenizer.dataState"),
            "html5lib:_tokenizer.py:393": ("html5lib/_tokenizer.py", 393, "HTMLTokenizer.tagOpenState"),            
            "html5lib:html5parser.py:209": ("html5lib/html5parser.py", 209, "HTMLParser::mainLoop"),
            "html5lib:html5parser.py:600": ("html5lib/html5parser.py", 600, "InitialPhase.processEOF"),
            "html5lib:html5parser.py:981": ("html5lib/html5parser.py", 981, "InBodyPhase::processCharacters"),
        },
        "medium": {
            "html5lib:html5parser.py:254": ("html5lib/html5parser.py", 254, "HTMLParser::mainLoop"),
            "html5lib:html5parser.py:635": ("html5lib/html5parser.py", 635, "BeforeHtmlPhase::processEndTag"),
            "html5lib:html5parser.py:1052": ("html5lib/html5parser.py", 1052, "InBodyPhase.startTagListItem"),
            "html5lib:html5parser.py:1054": ("html5lib/html5parser.py", 1054, "InBodyPhase::startTagListItem"),
            "html5lib:html5parser.py:1073": ("html5lib/html5parser.py", 1073, "InBodyPhase::startTagHeading"),
            "html5lib:html5parser.py:1076": ("html5lib/html5parser.py", 1076, "InBodyPhase.startTagHeading"),
            "html5lib:html5parser.py:1086": ("html5lib/html5parser.py", 1086, "InBodyPhase::startTagA"),
            "html5lib:html5parser.py:1249": ("html5lib/html5parser.py", 1249, "InBodyPhase::startTagRpRt"),
            "html5lib:html5parser.py:1297": ("html5lib/html5parser.py", 1297, "InBodyPhase::endTagP"),
            "html5lib:html5parser.py:1572": ("html5lib/html5parser.py", 1572, "InBodyPhase::endTagOther"),
        },
        "hard": {
            "html5lib:html5parser.py:248": ("html5lib/html5parser.py", 248, "HTMLParser::mainLoop"),
            "html5lib:html5parser.py:1029": ("html5lib/html5parser.py", 1029, "InBodyPhase::startTagPreListing"),
            "html5lib:html5parser.py:1125": ("html5lib/html5parser.py", 1125, "InBodyPhase::startTagXmp"),
            "html5lib:html5parser.py:1329": ("html5lib/html5parser.py", 1329, "InBodyPhase::endTagBlock"),
            "html5lib:html5parser.py:1334": ("html5lib/html5parser.py", 1334, "InBodyPhase::endTagBlock"),
        },
        "extreme_hard": {
            "html5lib:_tokenizer.py:1582": ("html5lib/_tokenizer.py", 1582, "HTMLTokenizer::afterDoctypeSystemKeywordState"),
            "html5lib:_tokenizer.py:1631": ("html5lib/_tokenizer.py", 1631, "HTMLTokenizer::doctypeSystemIdentifierDoubleQuotedState"),
            "html5lib:_tokenizer.py:1635": ("html5lib/_tokenizer.py", 1635, "HTMLTokenizer::doctypeSystemIdentifierDoubleQuotedState"),
            "html5lib:html5parser.py:373": ("html5lib/html5parser.py", 373, "HTMLParser.resetInsertionMode"),
            "html5lib:html5parser.py:1099": ("html5lib/html5parser.py", 1099, "InBodyPhase.startTagNobr"),        
        },
        "unreachable": {
            "html5lib:html5parser.py:490": ("html5lib/html5parser.py", 490, "InitialPhase.processDoctype"),
            "html5lib:html5parser.py:988": ("html5lib/html5parser.py", 988, "InBodyPhase::processCharacters"),
            "html5lib:html5parser.py:1133": ("html5lib/html5parser.py", 1133, "InBodyPhase::startTagTable"),
            "html5lib:html5parser.py:1349": ("html5lib/html5parser.py", 1349, "InBodyPhase.endTagForm"),
            "html5lib:html5parser.py:1512": ("html5lib/html5parser.py", 1512, "InBodyPhase.endTagFormatting"),
            "html5lib:html5parser.py:1783": ("html5lib/html5parser.py", 1783, "InTablePhase.endTagTable"),
            "html5lib:html5parser.py:1904": ("html5lib/html5parser.py", 1904, "InCaptionPhase.endTagCaption"),
            "html5lib:html5parser.py:2240": ("html5lib/html5parser.py", 2240, "InCellPhase.endTagTableCell"),            
        },
    },
    "filesystem_spec": {
        "easy": {
            "fsspec:asyn.py:34": ("fsspec/asyn.py", 34, "get_lock"),
            "fsspec:asyn.py:92": ("fsspec/asyn.py", 92, "sync"),
            "fsspec:asyn.py:930": ("fsspec/asyn.py", 930, "mirror_sync_methods"),
            "fsspec:asyn.py:940": ("fsspec/asyn.py", 940, "mirror_sync_methods"),
            "fsspec:implementations:http.py:124": ("fsspec/implementations/http.py", 124, "HTTPFileSystem::close_session"),
            "fsspec:implementations:http.py:137": ("fsspec/implementations/http.py", 137, "HTTPFileSystem::set_session"),
            "fsspec:spec.py:77": ("fsspec/spec.py", 77, "_Cached::__call__"),
            "fsspec:spec.py:86": ("fsspec/spec.py", 86, "_Cached::__call__"),
        },
        "medium": {
            "fsspec:asyn.py:96": ("fsspec/asyn.py", 96, "sync"),
        },
        "hard": {
            "fsspec:asyn.py:101": ("fsspec/asyn.py", 101, "sync"),
            "fsspec:implementations:http.py:127": ("fsspec/implementations/http.py", 127, "HTTPFileSystem::close_session"),
            "fsspec:implementations:http.py:131": ("fsspec/implementations/http.py", 131, "HTTPFileSystem::close_session"),
        },
        "unreachable": {
            "fsspec:spec.py:307": ("fsspec/spec.py", 307, "AbstractFileSystem::makedirs"),
        },
    },
    "rich": {
        "easy": {
            "rich:cells.py:89": ("rich/cells.py", 89, "get_character_cell_size"),
            "rich:console.py:1029": ("rich/console.py", 1029, "Console::size"),
            "rich:console.py:1036": ("rich/console.py", 1036, "Console::size"),
            "rich:console.py:1568": ("rich/console.py", 1568, "Console::check_text"),
            "rich:console.py:2057": ("rich/console.py", 2057, "Console::_write_buffer"),
            "rich:markdown.py:352": ("rich/markdown.py", 352, "ListElement.__rich_console__"),
            "rich:markdown.py:613": ("rich/markdown.py", 613, "Markdown.__rich_console__"),
            "rich:segment.py:351": ("rich/segment.py", 351, "Segment.adjust_line_length"),
            "rich:style.py:400": ("rich/style.py", 400, "Style.pick_first"),
            "rich:syntax.py:483": ("rich/syntax.py", 483, "Syntax.highlight"),
            "rich:syntax.py:841": ("rich/syntax.py", 841, "Syntax._get_code_index_for_syntax_position"),
            "rich:text.py:413": ("rich/text.py", 413, "Text.plain"),
        },
        "medium": {
            "rich:style.py:362": ("rich/style.py", 362, "Style._make_ansi_codes"),
            "rich:syntax.py:162": ("rich/syntax.py", 162, "PygmentsSyntaxTheme::get_style_for_token"),
            "rich:syntax.py:440": ("rich/syntax.py", 440, "Syntax::lexer"),
            "rich:syntax.py:445": ("rich/syntax.py", 445, "Syntax::default_lexer"),
            "rich:text.py:583": ("rich/text.py", 583, "Text.extend_style"),
            "rich:text.py:796": ("rich/text.py", 796, "Text::join"),
            "rich:text.py:1156": ("rich/text.py", 1156, "Text.divide"),
            "rich:text.py:1162": ("rich/text.py", 1162, "Text::divide"),
        },
        "hard": {
            "rich:syntax.py:160": ("rich/syntax.py", 160, "PygmentsSyntaxTheme::get_style_for_token"),
        },
        "extreme_hard": {
            "rich:cells.py:106": ("rich/cells.py", 106, "set_cell_size"),
        },
        "unreachable": {
            "rich:cells.py:109": ("rich/cells.py", 109, "set_cell_size"),
            "rich:table.py:649": ("rich/table.py", 649, "Table._get_cells"),
            "rich:table.py:655": ("rich/table.py", 655, "Table._get_cells"),
            "rich:table.py:661": ("rich/table.py", 661, "Table._get_cells"),            
            "rich:text.py:480": ("rich/text.py", 480, "Text::stylize"),
        },
    },
    "wamr": {
        "easy": {
            "core:iwasm:aot:aot_loader.c:95": ("core/iwasm/aot/aot_loader.c", 95, "check_buf"),
            "core:iwasm:aot:aot_loader.c:319": ("core/iwasm/aot/aot_loader.c", 319, "loader_mmap"),
            "core:iwasm:aot:aot_loader.c:325": ("core/iwasm/aot/aot_loader.c", 325, "loader_mmap"),
            "core:iwasm:aot:aot_loader.c:367": ("core/iwasm/aot/aot_loader.c", 367, "load_string"),
            "core:iwasm:aot:aot_loader.c:376": ("core/iwasm/aot/aot_loader.c", 376, "load_string"),
            "core:iwasm:aot:aot_loader.c:456": ("core/iwasm/aot/aot_loader.c", 456, "check_machine_info"),
            "core:iwasm:aot:aot_loader.c:547": ("core/iwasm/aot/aot_loader.c", 547, "load_target_info_section"),
            "core:iwasm:aot:aot_loader.c:588": ("core/iwasm/aot/aot_loader.c", 588, "load_target_info_section"),
            "core:iwasm:aot:aot_loader.c:605": ("core/iwasm/aot/aot_loader.c", 605, "load_target_info_section"),
            "core:iwasm:aot:aot_loader.c:666": ("core/iwasm/aot/aot_loader.c", 666, "load_native_symbol_section"),
        },
        "medium": {
            "core:iwasm:aot:aot_loader.c:4120": ("core/iwasm/aot/aot_loader.c", 4120, "resolve_execute_mode"),
            "core:iwasm:aot:aot_loader.c:4236": ("core/iwasm/aot/aot_loader.c", 4236, "aot_load_from_aot_file"),
            "core:iwasm:aot:aot_loader.c:4312": ("core/iwasm/aot/aot_loader.c", 4312, "load"),
        },
        "hard": {
            "core:iwasm:aot:aot_loader.c:417": ("core/iwasm/aot/aot_loader.c", 417, "get_aot_file_target"),
        },
        "extreme_hard": {
            "core:iwasm:aot:aot_loader.c:916": ("core/iwasm/aot/aot_loader.c", 916, "load_custom_section"),
            "core:iwasm:aot:aot_loader.c:1132": ("core/iwasm/aot/aot_loader.c", 1132, "load_init_exp"),
            "core:iwasm:aot:aot_loader.c:1304": ("core/iwasm/aot/aot_loader.c", 1304, "load_init_exp"),
            "core:iwasm:aot:aot_loader.c:4013": ("core/iwasm/aot/aot_loader.c", 4013, "load_from_sections"),
        },
        "unreachable": {
            "core:iwasm:aot:aot_loader.c:660": ("core/iwasm/aot/aot_loader.c", 660, "load_native_symbol_section"),
            "core:iwasm:aot:aot_loader.c:698": ("core/iwasm/aot/aot_loader.c", 698, "load_native_symbol_section"),
            "core:iwasm:aot:aot_loader.c:967": ("core/iwasm/aot/aot_loader.c", 967, "destroy_import_memories"),
            "core:iwasm:aot:aot_loader.c:1013": ("core/iwasm/aot/aot_loader.c", 1013, "load_mem_init_data_list"),
        },
    },
    "md4c": {
        "easy": {
            "src:md4c-html.c:134": ("src/md4c-html.c", 134, "render_url_escaped"),
            "src:md4c-html.c:163": ("src/md4c-html.c", 163, "hex_val"),            
            "src:md4c-html.c:240": ("src/md4c-html.c", 240, "render_entity"),
            "src:md4c-html.c:275": ("src/md4c-html.c", 275, "render_open_ol_block"),
            "src:md4c-html.c:290": ("src/md4c-html.c", 290, "render_open_li_block"),
            "src:md4c-html.c:304": ("src/md4c-html.c", 304, "render_open_code_block"),
            "src:md4c-html.c:320": ("src/md4c-html.c", 320, "render_open_td_block"),
            "src:md4c-html.c:333": ("src/md4c-html.c", 333, "render_open_a_span"),
            "src:md4c-html.c:464": ("src/md4c-html.c", 464, "enter_span_callback"),
            "src:md4c-html.c:479": ("src/md4c-html.c", 479, "leave_span_callback"),            
            "src:md4c-html.c:522": ("src/md4c-html.c", 522, "debug_log_callback"),
        },
        "unreachable": {
            "src:md4c-html.c:190": ("src/md4c-html.c", 190, "render_utf8_codepoint"),
            "src:md4c-html.c:210": ("src/md4c-html.c", 210, "render_entity"),
            "src:md4c-html.c:353": ("src/md4c-html.c", 353, "render_close_img_span"),            
            "src:md4c-html.c:560": ("src/md4c-html.c", 560, "md_html"),
        },
    },
    "libbpf": {
        "easy": {
            "src:libbpf.c:244": ("src/libbpf.c", 244, "__base_pr"),
            "src:libbpf.c:313": ("src/libbpf.c", 313, "pr_perm_msg"),
            "src:libbpf.c:879": ("src/libbpf.c", 879, "bpf_object__add_programs"),
            "src:libbpf.c:894": ("src/libbpf.c", 894, "bpf_object__add_programs"),
            "src:libbpf.c:983": ("src/libbpf.c", 983, "find_member_by_name"),
            "src:libbpf.c:8079": ("src/libbpf.c", 8079, "bpf_object__open_mem"),
            "src:libbpf.c:8082": ("src/libbpf.c", 8082, "bpf_object__open_mem"),
            "src:libbpf.c:9053": ("src/libbpf.c", 9053, "bpf_object__close"),
            "src:libbpf.c:9089": ("src/libbpf.c", 9089, "bpf_object__close"),
            "src:libbpf.c:10601": ("src/libbpf.c", 10601, "libbpf_get_error"),
        },
        "unreachable": {
            "src:libbpf.c:827": ("src/libbpf.c", 827, "bpf_object__init_prog"),
            "src:libbpf.c:1065": ("src/libbpf.c", 1065, "bpf_map__is_struct_ops"),
            "src:libbpf.c:1412": ("src/libbpf.c", 1412, "init_struct_ops_maps"),
            "src:libbpf.c:1659": ("src/libbpf.c", 1659, "bpf_object__init_kversion"),
            "src:libbpf.c:1999": ("src/libbpf.c", 1999, "bpf_object__init_global_data_maps"),
        },
    },
    "varnish": {
        "easy": {
            "bin:varnishd:cache:cache_esi_parse.c:287": ("bin/varnishd/cache/cache_esi_parse.c", 287, "vep_emit_verbatim"),
            "bin:varnishd:cache:cache_esi_parse.c:347": ("bin/varnishd/cache/cache_esi_parse.c", 347, "vep_mark_common"),
            "bin:varnishd:cache:cache_esi_parse.c:409": ("bin/varnishd/cache/cache_esi_parse.c", 409, "vep_do_comment"),
            "bin:varnishd:cache:cache_esi_parse.c:450": ("bin/varnishd/cache/cache_esi_parse.c", 450, "include_attr_src"),
            "bin:varnishd:cache:cache_esi_parse.c:583": ("bin/varnishd/cache/cache_esi_parse.c", 583, "vep_do_include"),
            "bin:varnishd:cache:cache_esi_parse.c:774": ("bin/varnishd/cache/cache_esi_parse.c", 774, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:876": ("bin/varnishd/cache/cache_esi_parse.c", 876, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:1008": ("bin/varnishd/cache/cache_esi_parse.c", 1008, "VEP_Parse"),
        },
        "medium": {
            "bin:varnishd:cache:cache_esi_parse.c:240": ("bin/varnishd/cache/cache_esi_parse.c", 240, "vep_match"),
            "bin:varnishd:cache:cache_esi_parse.c:458": ("bin/varnishd/cache/cache_esi_parse.c", 458, "include_attr_src"),
            "bin:varnishd:cache:cache_esi_parse.c:536": ("bin/varnishd/cache/cache_esi_parse.c", 536, "vep_do_include"),
            "bin:varnishd:cache:cache_esi_parse.c:715": ("bin/varnishd/cache/cache_esi_parse.c", 715, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:1117": ("bin/varnishd/cache/cache_esi_parse.c", 1117, "VEP_Finish"),
        },
        "hard": {
            "bin:varnishd:cache:cache_esi_parse.c:344": ("bin/varnishd/cache/cache_esi_parse.c", 344, "vep_mark_common"),
            "bin:varnishd:cache:cache_esi_parse.c:557": ("bin/varnishd/cache/cache_esi_parse.c", 557, "vep_do_include"),
            "bin:varnishd:cache:cache_esi_parse.c:568": ("bin/varnishd/cache/cache_esi_parse.c", 568, "vep_do_include"),
            "bin:varnishd:cache:cache_esi_parse.c:662": ("bin/varnishd/cache/cache_esi_parse.c", 662, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:682": ("bin/varnishd/cache/cache_esi_parse.c", 682, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:709": ("bin/varnishd/cache/cache_esi_parse.c", 709, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:900": ("bin/varnishd/cache/cache_esi_parse.c", 900, "VEP_Parse"),
        },
        "extreme_hard": {
            "bin:varnishd:cache:cache_esi_parse.c:695": ("bin/varnishd/cache/cache_esi_parse.c", 695, "VEP_Parse"),
        },
        "unreachable": {
            "bin:varnishd:cache:cache_esi_parse.c:672": ("bin/varnishd/cache/cache_esi_parse.c", 672, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:803": ("bin/varnishd/cache/cache_esi_parse.c", 803, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:856": ("bin/varnishd/cache/cache_esi_parse.c", 856, "VEP_Parse"),
            "bin:varnishd:cache:cache_esi_parse.c:977": ("bin/varnishd/cache/cache_esi_parse.c", 977, "VEP_Parse"),
        },
    },
    "clib": {
        "easy": {
            "src:common:clib-package.c:184": ("src/common/clib-package.c", 184, "json_object_get_string_safe"),
            "src:common:clib-package.c:249": ("src/common/clib-package.c", 249, "clib_package_load_from_manifest"),
            "src:common:clib-package.c:323": ("src/common/clib-package.c", 323, "parse_package_deps"),
            "src:common:clib-package.c:345": ("src/common/clib-package.c", 345, "parse_package_deps"),
            "src:common:clib-package.c:470": ("src/common/clib-package.c", 470, "clib_package_new"),
            "src:common:clib-package.c:477": ("src/common/clib-package.c", 477, "clib_package_new"),
            "src:common:clib-package.c:544": ("src/common/clib-package.c", 544, "clib_package_new"),
            "src:common:clib-package.c:564": ("src/common/clib-package.c", 564, "clib_package_new"),
            "src:common:clib-package.c:571": ("src/common/clib-package.c", 571, "clib_package_new"),
            "src:common:clib-package.c:1705": ("src/common/clib-package.c", 1705, "clib_package_free"),
        },
        "medium": {
            "src:common:clib-package.c:565": ("src/common/clib-package.c", 565, "clib_package_new"),
            "src:common:clib-package.c:573": ("src/common/clib-package.c", 573, "clib_package_new"),
        },
        "unreachable": {
            "src:common:clib-package.c:479": ("src/common/clib-package.c", 479, "clib_package_new"),
            "src:common:clib-package.c:483": ("src/common/clib-package.c", 483, "clib_package_new"),
            "src:common:clib-package.c:519": ("src/common/clib-package.c", 519, "clib_package_new"),
            "src:common:clib-package.c:582": ("src/common/clib-package.c", 582, "clib_package_new"),
            "src:common:clib-package.c:591": ("src/common/clib-package.c", 591, "clib_package_new"),
        },
    },
    "cmark": {
        "easy": {
            "src:blocks.c:144": ("src/blocks.c", 144, "is_blank"),
            "src:blocks.c:151": ("src/blocks.c", 151, "is_blank"),
            "src:blocks.c:188": ("src/blocks.c", 188, "add_line"),            
            "src:blocks.c:217": ("src/blocks.c", 217, "remove_trailing_blank_lines"),
            "src:blocks.c:277": ("src/blocks.c", 277, "finalize"),
            "src:blocks.c:316": ("src/blocks.c", 316, "finalize"),
            "src:blocks.c:326": ("src/blocks.c", 326, "finalize"),
            "src:blocks.c:531": ("src/blocks.c", 531, "finalize_document"),
            "src:blocks.c:644": ("src/blocks.c", 644, "cmark_parser_feed"),
            "src:blocks.c:1035": ("src/blocks.c", 1035, "open_new_blocks"),
        },
        "unreachable": {
            "src:blocks.c:228": ("src/blocks.c", 228, "remove_trailing_blank_lines"),
            "src:blocks.c:303": ("src/blocks.c", 303, "finalize"),
            "src:blocks.c:488": ("src/blocks.c", 488, "parse_list_marker"),
            "src:blocks.c:590": ("src/blocks.c", 590, "S_parser_feed"),
            "src:blocks.c:593": ("src/blocks.c", 593, "S_parser_feed"),
        },
    },
    "cpp-httplib": {
        "easy": {
            "httplib.h:3878": ("httplib.h", 3878, "create_socket"),
            "httplib.h:3986": ("httplib.h", 3986, "create_socket"),
            "httplib.h:4068": ("httplib.h", 4068, "bind_ip_address"),
            "httplib.h:4080": ("httplib.h", 4080, "bind_ip_address"),
            "httplib.h:4145": ("httplib.h", 4145, "bind_ip_address"),
            "httplib.h:4705": ("httplib.h", 4705, "read_headers"),
            "httplib.h:5244": ("httplib.h", 5244, "write_content_chunked"),
            "httplib.h:5689": ("httplib.h", 5689, "FormDataParser::parse"),
            "httplib.h:6624": ("httplib.h", 6624, "decode_path_component"),
            "httplib.h:7612": ("httplib.h", 7612, "Server::parse_request_line"),
        },
        "medium": {
            "httplib.h:5528": ("httplib.h", 5528, "parse_accept_header"),
            "httplib.h:6725": ("httplib.h", 6725, "decode_query_component"),
        },
        "extreme_hard": {
            "httplib.h:7855": ("httplib.h", 7855, "Server::read_content"),
        },
        "unreachable": {
            "httplib.h:2711": ("httplib.h", 2711, "is_field_content"),
            "httplib.h:5503": ("httplib.h", 5503, "parse_accept_header"),
            "httplib.h:5618": ("httplib.h", 5618, "parse"),
            "httplib.h:5680": ("httplib.h", 5680, "parse"),
            "httplib.h:7640": ("httplib.h", 7640, "parse_request_line"),
        },
    },
    "libpng": {
        "easy": {
            "png.c:36": ("png.c", 36, "png_set_sig_bytes"),
            "png.c:58": ("png.c", 58, "png_sig_cmp"),
            "png.c:61": ("png.c", 61, "png_sig_cmp"),
            "png.c:86": ("png.c", 86, "png_zalloc"),
            "png.c:188": ("png.c", 188, "png_user_version_check"),
            "png.c:340": ("png.c", 340, "png_create_info_struct"),
            "png.c:351": ("png.c", 351, "png_create_info_struct"),
            "png.c:421": ("png.c", 421, "png_info_init_3"),
            "png.c:578": ("png.c", 578, "png_free_data"),
            "png.c:775": ("png.c", 775, "png_convert_to_rfc1123"),
        },
        "unreachable": {
            "png.c:465": ("png.c", 465, "png_free_data"),
            "png.c:2197": ("png.c", 2197, "png_icc_check_header"),
            "png.c:2222": ("png.c", 2222, "png_icc_check_header"),
            "png.c:2232": ("png.c", 2232, "png_icc_check_header"),
            "png.c:2240": ("png.c", 2240, "png_icc_check_header"),
        },
    },
    "guetzli": {
        "easy": {
            "guetzli:jpeg_data_reader.cc:163": ("guetzli/jpeg_data_reader.cc", 163, "ProcessSOF"),
            "guetzli:jpeg_data_reader.cc:243": ("guetzli/jpeg_data_reader.cc", 243, "ProcessSOS"),
            "guetzli:jpeg_data_reader.cc:338": ("guetzli/jpeg_data_reader.cc", 338, "ProcessDHT"),
            "guetzli:jpeg_data_reader.cc:386": ("guetzli/jpeg_data_reader.cc", 386, "ProcessDRI"),
            "guetzli:jpeg_data_reader.cc:649": ("guetzli/jpeg_data_reader.cc", 649, "RefineDCTBlock"),
            "guetzli:jpeg_data_reader.cc:743": ("guetzli/jpeg_data_reader.cc", 743, "ProcessRestart"),
            "guetzli:jpeg_data_reader.cc:939": ("guetzli/jpeg_data_reader.cc", 939, "ReadJpeg"),
            "guetzli:jpeg_data_reader.cc:1022": ("guetzli/jpeg_data_reader.cc", 1022, "ReadJpeg"),
            "guetzli:jpeg_data_reader.cc:1036": ("guetzli/jpeg_data_reader.cc", 1036, "ReadJpeg"),
            "guetzli:jpeg_data_reader.cc:1065": ("guetzli/jpeg_data_reader.cc", 1065, "ReadJpeg"),
        },
        "medium": {
            "guetzli:jpeg_data_reader.cc:198": ("guetzli/jpeg_data_reader.cc", 198, "ProcessSOS"),
            "guetzli:jpeg_data_reader.cc:231": ("guetzli/jpeg_data_reader.cc", 231, "ProcessSOS"),
            "guetzli:jpeg_data_reader.cc:287": ("guetzli/jpeg_data_reader.cc", 287, "ProcessDHT"),
        },
        "extreme_hard": {
            "guetzli:jpeg_data_reader.cc:185": ("guetzli/jpeg_data_reader.cc", 185, "ProcessSOS"),
        },
        "unreachable": {
            "guetzli:jpeg_data_reader.cc:320": ("guetzli/jpeg_data_reader.cc", 320, "ProcessDHT"),
            "guetzli:jpeg_data_reader.cc:351": ("guetzli/jpeg_data_reader.cc", 351, "ProcessDQT"),
            "guetzli:jpeg_data_reader.cc:655": ("guetzli/jpeg_data_reader.cc", 655, "RefineDCTBlock"),
            "guetzli:jpeg_data_reader.cc:700": ("guetzli/jpeg_data_reader.cc", 700, "RefineDCTBlock"),
            "guetzli:jpeg_data_reader.cc:956": ("guetzli/jpeg_data_reader.cc", 956, "ReadJpeg"),
        },
    },
    "exiv2": {
        "easy": {
            "src:xmp.cpp:112": ("src/xmp.cpp", 112, "check_internal"),
            "src:xmp.cpp:497": ("src/xmp.cpp", 497, "XmpData::eraseFamily"),
            "src:xmp.cpp:513": ("src/xmp.cpp", 513, "XmpParser::initialize"),
            "src:xmp.cpp:587": ("src/xmp.cpp", 587, "nsDumper"),
            "src:xmp.cpp:613": ("src/xmp.cpp", 613, "XmpParser::registeredNamespaces"),
            "src:xmp.cpp:839": ("src/xmp.cpp", 839, "XmpParser::encode"),
            "src:xmp.cpp:841": ("src/xmp.cpp", 841, "XmpParser::encode"),
            "src:xmp.cpp:849": ("src/xmp.cpp", 849, "XmpParser::encode"),
            "src:xmp.cpp:856": ("src/xmp.cpp", 856, "XmpParser::encode"),
            "src:xmp.cpp:873": ("src/xmp.cpp", 873, "XmpParser::encode"),
        },
        "unreachable": {
            "src:xmp.cpp:90": ("src/xmp.cpp", 90, "XMLValidator()::setError"),
            "src:xmp.cpp:133": ("src/xmp.cpp", 133, "XMLValidator()::startNamespace"),
            "src:xmp.cpp:457": ("src/xmp.cpp", 457, "XmpData::begin"),
            "src:xmp.cpp:747": ("src/xmp.cpp", 747, "XmpParser::decode"),
            "src:xmp.cpp:870": ("src/xmp.cpp", 870, "XmpParser::encode"),
        },
    },
}

VIBE_TARGETS = {
    "bleach": {
        "easy": {
            # from VIBE_FEATURE_ONLY_TARGETS
            "bleach:linkifier.py:183": ("bleach/linkifier.py", 183, "Linker.linkify"),
            "bleach:linkifier.py:273": ("bleach/linkifier.py", 273, "LinkifyFilter.extract_character_data"),
            "bleach:linkifier.py:278": ("bleach/linkifier.py", 278, "LinkifyFilter.extract_character_data"),
            "bleach:linkifier.py:284": ("bleach/linkifier.py", 284, "LinkifyFilter.extract_character_data"),
            "bleach:linkifier.py:286": ("bleach/linkifier.py", 286, "LinkifyFilter.extract_character_data"),
            # from VIBE_OVERALL_TARGETS
            "bleach:linkifier.py:438": ("bleach/linkifier.py", 438, "LinkifyFilter.handle_links"),
            "bleach:linkifier.py:444": ("bleach/linkifier.py", 444, "LinkifyFilter.handle_links"),
            "bleach:linkifier.py:449": ("bleach/linkifier.py", 449, "LinkifyFilter.handle_links"),
            "bleach:linkifier.py:607": ("bleach/linkifier.py", 607, "LinkifyFilter._should_skip"),
            "bleach:linkifier.py:648": ("bleach/linkifier.py", 648, "LinkifyFilter._handle_normal_state"),
            "bleach:linkifier.py:652": ("bleach/linkifier.py", 652, "LinkifyFilter._handle_buffering_state"),
            "bleach:linkifier.py:658": ("bleach/linkifier.py", 658, "LinkifyFilter._handle_buffering_state"),
            "bleach:linkifier.py:661": ("bleach/linkifier.py", 661, "LinkifyFilter._handle_start_tag"),
            "bleach:linkifier.py:662": ("bleach/linkifier.py", 662, "LinkifyFilter._handle_start_tag"),
            "bleach:linkifier.py:669": ("bleach/linkifier.py", 669, "LinkifyFilter._handle_start_tag"),
            "bleach:linkifier.py:673": ("bleach/linkifier.py", 673, "LinkifyFilter._handle_end_tag"),
            "bleach:linkifier.py:678": ("bleach/linkifier.py", 678, "LinkifyFilter._handle_end_tag"),
            "bleach:linkifier.py:698": ("bleach/linkifier.py", 698, "LinkifyFilter._handle_other_token"),
            "bleach:linkifier.py:718": ("bleach/linkifier.py", 718, "LinkifyFilter.__iter__"),
            "bleach:linkifier.py:720": ("bleach/linkifier.py", 720, "LinkifyFilter.__iter__"),
        },
        "medium": {
            # from VIBE_FEATURE_ONLY_TARGETS
            "bleach:linkifier.py:280": ("bleach/linkifier.py", 280, "LinkifyFilter.extract_character_data"),
        },
        "unreachable": {
            # from VIBE_FEATURE_ONLY_TARGETS
            "bleach:linkifier.py:276": ("bleach/linkifier.py", 276, "LinkifyFilter.extract_character_data"),
            "bleach:linkifier.py:282": ("bleach/linkifier.py", 282, "LinkifyFilter.extract_character_data"),
            "bleach:linkifier.py:288": ("bleach/linkifier.py", 288, "LinkifyFilter.extract_character_data"),
            # from VIBE_OVERALL_TARGETS
            "bleach:linkifier.py:436": ("bleach/linkifier.py", 436, "LinkifyFilter.handle_links"),
            "bleach:linkifier.py:608": ("bleach/linkifier.py", 608, "LinkifyFilter._should_skip"),
            "bleach:linkifier.py:667": ("bleach/linkifier.py", 667, "LinkifyFilter._handle_start_tag"),
            "bleach:linkifier.py:676": ("bleach/linkifier.py", 676, "LinkifyFilter._handle_end_tag"),
            "bleach:linkifier.py:685": ("bleach/linkifier.py", 685, "LinkifyFilter._handle_characters"),
            "bleach:linkifier.py:696": ("bleach/linkifier.py", 696, "LinkifyFilter._handle_other_token"),
        },
    },
    "html5lib-python": {
        "unreachable": {
            # from VIBE_OVERALL_TARGETS
            "html5lib:_inputstream.py:190": ("html5lib/_inputstream.py", 190, "HTMLUnicodeInputStream.__init__"),
            "html5lib:_inputstream.py:265": ("html5lib/_inputstream.py", 265, "HTMLUnicodeInputStream.readChunk"),
            "html5lib:html5parser.py:137": ("html5lib/html5parser.py", 137, "HTMLParser._initialize_parsing_context"),
            "html5lib:html5parser.py:217": ("html5lib/html5parser.py", 217, "HTMLParser._ensure_handlers_initialized"),
            "html5lib:html5parser.py:219": ("html5lib/html5parser.py", 219, "HTMLParser._ensure_handlers_initialized"),
            "html5lib:html5parser.py:229": ("html5lib/html5parser.py", 229, "HTMLParser._validate_integrity"),
            "html5lib:html5parser.py:232": ("html5lib/html5parser.py", 232, "HTMLParser._validate_integrity"),
            "html5lib:html5parser.py:250": ("html5lib/html5parser.py", 250, "HTMLParser.mainLoop"),
            "html5lib:html5parser.py:262": ("html5lib/html5parser.py", 262, "HTMLParser.mainLoop"),
            "html5lib:html5parser.py:279": ("html5lib/html5parser.py", 279, "HTMLParser.mainLoop"),
            "html5lib:html5parser.py:1337": ("html5lib/html5parser.py", 1337, "InBodyPhase.startTagTemplate"),
            "html5lib:html5parser.py:1339": ("html5lib/html5parser.py", 1339, "InBodyPhase.startTagTemplate"),
            "html5lib:treebuilders:base.py:334": ("html5lib/treebuilders/base.py", 334, "TreeBuilder.insertShadowRoot"),
        },
    },
    "rich": {
        "easy": {
            # from VIBE_FEATURE_ONLY_TARGETS
            "rich:markdown.py:556": ("rich/markdown.py", 556, "Markdown.__init__"),
            "rich:markdown.py:560": ("rich/markdown.py", 560, "Markdown.__init__"),
            "rich:syntax.py:285": ("rich/syntax.py", 285, "Syntax.__init__"),
            "rich:text.py:1213": ("rich/text.py", 1213, "Text.wrap"),
        },
        "medium": {
            # from VIBE_FEATURE_ONLY_TARGETS
            "rich:table.py:479": ("rich/table.py", 479, "Table.__rich_console__"),
        },
        "unreachable": {
            # from VIBE_FEATURE_ONLY_TARGETS
            "rich:markdown.py:554": ("rich/markdown.py", 554, "Markdown.__init__"),
            "rich:markdown.py:558": ("rich/markdown.py", 558, "Markdown.__init__"),
            "rich:panel.py:22": ("rich/panel.py", 22, "HolographicCompositor.add_panel"),
            "rich:syntax.py:283": ("rich/syntax.py", 283, "Syntax.__init__"),
            "rich:text.py:1214": ("rich/text.py", 1214, "Text.wrap"),
        },
    },
}

HARNESS_PROMPTS = {
    "lark-parser":  (2, "This program requires two distinct input strings. Please provide these inputs, separated by a single blank line. If your generated input is as follows:\n```\ninput1\n\ninput2\\ninput3\n```\nWe will replace the `grammar` variable with 'input1' and replace `text` with 'input2\\ninput3' in the `TestOneInput()` function and the fuzzer will then run the `Lark()` and `parse()` function on that input."),
    "bleach": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will replace the `data` variable with that string in the `TestOneInput()` function and the fuzzer will then run the `bleach.linkify()` function on that input."),
    "html5lib-python": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will replace the `fdp.ConsumeUnicodeNoSurrogates(sys.maxsize)` with that string 'input\\ninput' in the `TestOneInput()` function and the fuzzer will then run the html5lib.parse()` function on that input."),
    "rich": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will replace the `markdown` variable with that string in the `TestOneInput()` function and the fuzzer will then run with that input."),
    "filesystem_spec": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will replace the `path` variable with that string 'input\\ninput' in the `TestOneInput()` function and the fuzzer will then run the `h.put_file()` and `h.open()` functions on that input."),

    "wamr": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "md4c": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "libbpf": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "varnish": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "clib": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    
    "cmark": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "cpp-httplib": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "libpng": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "guetzli": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
    "exiv2": (1, "This program requires one input string. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will assign the value of `data` to that input string 'input\\ninput' and assgin the value of `size` to the length of that input string at the beginning of the `LLVMFuzzerTestOneInput()` function and the fuzzer will then run the function on that input."),
}

# ARVO CVE targets: ARVO_TARGETS[project_name][cve_id] = (filepath, line_number, function_name, cve_pattern)
# T6: the 50 CVEs of data/target-arvo/benchmark.json. Other ARVO-style cases, such as the knowledge-cutoff study
# set data/post-cutoff/benchmark.json (not part of the benchmark), take these from their benchmark json entry.
ARVO_TARGETS = {
    "serenity": {
        "42490094": ("Libraries/LibRegex/RegexLexer.cpp", 69, "regex::Lexer::back(unsigned long)", "AddressSanitizer: heap-buffer-overflow"),
        "42490103": ("Shell/Parser.cpp", 1380, "Shell::Parser::parse_glob()", "UndefinedBehaviorSanitizer: undefined-behavior"),
        "42490130": ("Libraries/LibCore/puff.cpp", 300, "decode(state*, huffman const*)", "AddressSanitizer: heap-buffer-overflow"),
        "42490150": ("Libraries/LibGfx/BMPLoader.cpp", 219, "Gfx::Streamer::read_u8()", "AddressSanitizer: heap-buffer-overflow"),
        "42490167": ("Libraries/LibCore/puff.cpp", 300, "decode(state*, huffman const*)", "AddressSanitizer: heap-buffer-overflow"),
        "42490247": ("Libraries/LibGfx/GIFLoader.cpp", 379, "Gfx::decode_frame(Gfx::GIFLoadingContext&, unsigned long)", "AddressSanitizer: global-buffer-overflow"),
        "42491388": ("Libraries/LibJS/Heap/Heap.cpp", 149, "JS::Heap::gather_conservative_roots(AK::HashTable<JS::Cell*, AK::Traits<JS::Cell*> >&)", "AddressSanitizer: stack-buffer-overflow"),
        "42491468": ("Libraries/LibTTF/Font.cpp", 48, "TTF::be_u16(unsigned char const*)", "AddressSanitizer: heap-buffer-overflow"),
        "42492610": ("AK/Format.h", 227, "AK::VariadicFormatParams<>::VariadicFormatParams()", "undefined-behavior"),
        "42492700": ("Userland/Libraries/LibGfx/BMPLoader.cpp", 886, "Gfx::decode_bmp_color_table(Gfx::BMPLoadingContext&)", "undefined-behavior"),
    },
    "assimp": {
        "42486052": ("contrib/openddlparser/code/OpenDDLParser.cpp", 551, "ODDLParser::OpenDDLParser::parseIdentifier(char*, char*, ODDLParser::Text**)", "AddressSanitizer: heap-buffer-overflow"),
        "42486054": ("include/assimp/IOStreamBuffer.h", 291, "Assimp::IOStreamBuffer<char>::getNextDataLine(std::__1::vector<char, std::__1::allocator<char> >&, char)", "AddressSanitizer: heap-buffer-overflow"),
        "42486096": ("code/AssetLib/MDL/MDLLoader.cpp", 604, "Assimp::MDLImporter::InternReadFile_3DGS_MDL345()", "AddressSanitizer: heap-buffer-overflow"),
        "42486152": ("code/Common/RemoveComments.cpp", 69, "Assimp::CommentRemover::RemoveLineComments(char const*, char*, char)", "AddressSanitizer: heap-buffer-overflow"),
        "42486916": ("code/AssetLib/Obj/ObjFileMtlImporter.cpp", 229, "Assimp::ObjFileMtlImporter::getFloatValue(float&)", "AddressSanitizer: SEGV"),
        "42487095": ("code/AssetLib/HMP/HMPLoader.cpp", 457, "Assimp::HMPImporter::ReadFirstSkin(unsigned int, unsigned char const*, unsigned char const**)", "AddressSanitizer: heap-buffer-overflow"),
        "42488125": ("code/AssetLib/Obj/ObjFileImporter.cpp", 468, "Assimp::ObjFileImporter::createVertexArray(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, unsigned int, aiMesh*, unsigned int)", "AddressSanitizer: heap-use-after-free"),
        "42489445": ("code/AssetLib/ASE/ASEParser.cpp", 496, "Assimp::ASE::Parser::ParseLV1MaterialListBlock()", "undefined-behavior"),
        "42494198": ("contrib/openddlparser/code/OpenDDLParser.cpp", 495, "ODDLParser::OpenDDLParser::normalizeBuffer(std::__1::vector<char, std::__1::allocator<char> >&)", "AddressSanitizer: heap-buffer-overflow"),
        "42495340": ("include/assimp/XmlParser.h", 91, "Assimp::TXmlParser<pugi::xml_node>::clear()", "AddressSanitizer: heap-use-after-free"),
    },
    "wasm3": {
        "42495613": ("source/m3_compile.c", 2207, "Compile_BlockStatements", "MemorySanitizer: SEGV"),
        "42495614": ("source/m3_env.c", 61, "Environment_Release", "MemorySanitizer: use-of-uninitialized-value"),
        "42495624": ("source/m3_compile.c", 2206, "Compile_BlockStatements", "AddressSanitizer: global-buffer-overflow"),
        "42495627": ("source/m3_env.c", 201, "ForEachModule", "AddressSanitizer: stack-overflow"),
        "42495628": ("source/m3_compile.c", 376, "PreserveRegisterIfOccupied", "undefined-behavior"),
        "42495632": ("source/m3_env.c", 496, "InitElements", "MemorySanitizer: use-of-uninitialized-value"),
        "42495642": ("source/m3_env.c", 986, "AcquireCodePageWithCapacity", "MemorySanitizer: SEGV"),
        "42495755": ("source/m3_code.c", 27, "NewCodePage", "AddressSanitizer: heap-buffer-overflow"),
        "42495801": ("source/m3_env.c", 474, "InitDataSegments", "AddressSanitizer: heap-buffer-overflow"),
        "42495805": ("source/m3_parse.c", 99, "ParseSection_Type", "AddressSanitizer: heap-buffer-overflow"),
    },
    "openh264": {
        "42473818": ("codec/decoder/core/src/decoder.cpp", 176, "WelsDec::ResetRefPicReferences(WelsDec::TagWelsDecoderContext* const&, WelsDec::SPicture* const&)", "AddressSanitizer: heap-use-after-free"),
        "42474468": ("codec/decoder/core/src/mv_pred.cpp", 1113, "WelsDec::MapColToList0(WelsDec::TagWelsDecoderContext*&, signed char const&, int const&)", "AddressSanitizer: heap-use-after-free"),
        "42474899": ("codec/decoder/core/src/decoder.cpp", 217, "WelsDec::DecreasePicBuff(WelsDec::TagWelsDecoderContext*, WelsDec::TagPicBuff**, int, int, int, int)", "AddressSanitizer: heap-use-after-free"),
        "42479359": ("codec/decoder/core/src/manage_dec_ref.cpp", 89, "WelsDec::SetUnRef(WelsDec::SPicture*)", "AddressSanitizer: heap-use-after-free"),
        "42479382": ("codec/decoder/core/src/manage_dec_ref.cpp", 89, "WelsDec::SetUnRef(WelsDec::SPicture*)", "AddressSanitizer: heap-use-after-free"),
        "42479588": ("codec/decoder/core/src/manage_dec_ref.cpp", 89, "WelsDec::SetUnRef(WelsDec::SPicture*)", "AddressSanitizer: heap-use-after-free"),
        "42479698": ("codec/decoder/core/src/manage_dec_ref.cpp", 89, "WelsDec::SetUnRef(WelsDec::SPicture*)", "AddressSanitizer: heap-use-after-free"),
        "42479699": ("codec/decoder/plus/src/welsDecoderExt.cpp", 1078, "WelsDec::CWelsDecoder::ReleaseBufferedReadyPicture(WelsDec::TagWelsDecoderContext*, unsigned char**, TagBufferInfo*)", "MemorySanitizer: use-of-uninitialized-value"),
        "42479702": ("codec/decoder/plus/src/welsDecoderExt.cpp", 505, "WelsDec::CWelsDecoder::SetOption(DECODER_OPTION, void*)", "AddressSanitizer: heap-use-after-free"),
        "42479832": ("codec/decoder/plus/src/welsDecoderExt.cpp", 715, "WelsDec::CWelsDecoder::DecodeFrame2WithCtx(WelsDec::TagWelsDecoderContext*, unsigned char const*, int, unsigned char**, TagBufferInfo*)", "UndefinedBehaviorSanitizer: SEGV"),
    },
    "opensc": {
        "42477333": ("src/libopensc/asn1.c", 573, "decode_bit_string", "AddressSanitizer: heap-buffer-overflow"),
        "42477334": ("src/libopensc/asn1.c", 573, "decode_bit_string", "AddressSanitizer: heap-buffer-overflow"),
        "42477340": ("src/libopensc/asn1.c", 1468, "asn1_decode_entry", "AddressSanitizer: heap-buffer-overflow"),
        "42477951": ("src/libopensc/pkcs15.c", 1882, "sc_pkcs15_free_object", "AddressSanitizer: heap-use-after-free"),
        "42479408": ("src/libopensc/pkcs15-prkey.c", 265, "sc_pkcs15_decode_prkdf_entry", "AddressSanitizer: bad-free"),
        "42479473": ("src/libopensc/pkcs15-pin.c", 270, "_validate_pin", "AddressSanitizer: heap-buffer-overflow"),
        "42479504": ("src/libopensc/pkcs15-coolkey.c", 291, "coolkey_get_certificate", "AddressSanitizer: heap-buffer-overflow"),
        "42479506": ("src/libopensc/card-coolkey.c", 343, "coolkey_v1_get_attribute_len", "AddressSanitizer: heap-buffer-overflow"),
        "42479512": ("src/libopensc/sc.c", 219, "bebytes2ushort", "AddressSanitizer: heap-buffer-overflow"),
        "42479513": ("src/tests/fuzzing/fuzz_pkcs15_reader.c", 129, "fuzz_reader_transmit", "AddressSanitizer: stack-buffer-overflow"),
    },
}

ARVO_HARNESS_PROMPTS = {
    "serenity": (1, "This program requires one input. Your generated input will be written to a file and passed as the argument to the fuzzing harness. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will write that input string to a file and the fuzzer will then run on that input."),
    "assimp": (1, "This program requires one input. Your generated input will be written to a file and passed as the argument to the fuzzing harness. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will write that input string to a file and the fuzzer will then run on that input."),
    "wasm3": (1, "This program requires one input. Your generated input will be written to a file and passed as the argument to the fuzzing harness. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will write that input string to a file and the fuzzer will then run on that input."),
    "openh264": (1, "This program requires one input. Your generated input will be written to a file and passed as the argument to the fuzzing harness. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will write that input string to a file and the fuzzer will then run on that input."),
    "opensc": (1, "This program requires one input. Your generated input will be written to a file and passed as the argument to the fuzzing harness. If your generated input is as follows:\n```\ninput\\ninput\n```\nWe will write that input string to a file and the fuzzer will then run on that input."),
}
